### ISSUE TITLE
🐛 An error occurred: Unknown HP pattern: 50 + 10 for each spell level above 5.

### ISSUE THREAD

**Issue by simonkingaby** [ebullient/ttrpg-convert-cli#591] opened 2024-12-11 03:49 UTC
I ran: ./ttrpg-convert.exe --index -o dm 5etools-mirror-2.github.io/data and after some warnings, got this error message:
[ ≡ƒ¢æ ERR] An error occurred: Unknown HP pattern: 50 + 10 for each spell level above 5.

I expected it to create the SRD folders in a dm folder.

[ ≡ƒ¢æ ERR] An error occurred: Unknown HP pattern: 50 + 10 for each spell level above 5.

## Configuration

- **OS**: Windows 11
- **CLI version**: ttrpg-convert version 2.3.18
Git commit: ed56f76
Build time: 2024-07-27T02:01:31Z
- **CLI type**: native command

**Sources**:
- enabled sources: 5etools-mirror-2.github.io\data
- custom templates (attach if possible) N/A

[ttrpg-convert.out.txt](https://github.com/user-attachments/files/18089236/ttrpg-convert.out.txt)

**Comment by simonkingaby** [comment] 2024-12-11 13:10
Can be fixed by adding:
```java
            } else if (hpString.matches("\\d+ \\+ \\d+ per spell level above \\d+")) {
                // matches 50 + 10 per spell level above 5th
                // nothing we can do right now
```
to ttrpg-src\src\main\java\dev\ebullient\convert\tools\dnd5e\Json2QuteMonster.java
line 635

Thanks,
Simon

**Comment by ebullient** [comment] 2024-12-11 23:55
This is probably already fixed in the snapshot.

Duplicate of #537

**Closed by ebullient** 2024-12-11 23:55 UTC
Labels: bug
